#!/bin/bash
set -euo pipefail

# Manages a generated ~/.ssh/rust-dev-containers.conf with one Host alias per
# rust-dev container, plus a one-time managed Include block in ~/.ssh/config.
# Run `regen` (default) after creating/removing containers.

SSH_DIR="${HOME}/.ssh"
MANAGED_CONF="${SSH_DIR}/rust-dev-containers.conf"
USER_CONFIG="${SSH_DIR}/config"
MARKER="# >>> rust-dev-docker (managed) >>>"

regen() {
    mkdir -p "$SSH_DIR"
    {
        echo "# Generated by rust-dev-docker - do not edit."
        echo "# Rebuild with: ./ssh-config.sh regen"
        echo
        while IFS=$'\t' read -r name port; do
            [ -n "$name" ] || continue
            printf 'Host %s\n    HostName localhost\n    Port %s\n    User root\n    StrictHostKeyChecking no\n    UserKnownHostsFile /dev/null\n\n' \
                "$name" "${port:-?}"
        done < <(docker ps -a --filter "label=rustdev=1" \
            --format '{{.Names}}\t{{.Label "rustdev.port"}}')
    } > "$MANAGED_CONF"
    chmod 600 "$MANAGED_CONF"

    touch "$USER_CONFIG"
    if ! grep -qF "$MARKER" "$USER_CONFIG"; then
        {
            echo "$MARKER"
            echo "Include ${MANAGED_CONF}"
            echo "# <<< rust-dev-docker (managed) <<<"
        } >> "$USER_CONFIG"
        echo "==> Added Include block to ~/.ssh/config"
    fi
}

case "${1:-regen}" in
    regen) regen ;;
    *) echo "Usage: $0 [regen]" >&2; exit 1 ;;
esac
